function(register_embedded_file FILE_PATH VARIABLE_NAME)
    get_property(CURRENT_FILES GLOBAL PROPERTY EMBEDDED_FILES_LIST)
    get_property(CURRENT_VARS GLOBAL PROPERTY EMBEDDED_VARIABLES_LIST)

    list(APPEND CURRENT_FILES "${FILE_PATH}")
    list(APPEND CURRENT_VARS "${VARIABLE_NAME}")
    
    set_property(GLOBAL PROPERTY EMBEDDED_FILES_LIST "${CURRENT_FILES}")
    set_property(GLOBAL PROPERTY EMBEDDED_VARIABLES_LIST "${CURRENT_VARS}")
    
    message(STATUS "Registered embedded file: ${FILE_PATH} as ${VARIABLE_NAME}")
endfunction()